# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/docs/sushi/configuration/                    │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: vital-records-fhir-messaging
canonical: http://mitre.org/fhir/vital-records-fhir-messaging
name: VitalRecordsFHIRMessagingIG
status: draft
version: 0.1.0
copyrightYear: 2021+
releaseLabel: ci-build
publisher:
  name: CDC NCHS
  url: http://example.org/example-publisher
license: CC0-1.0
fhirVersion: 4.0.1
dependencies:
  hl7.fhir.us.core: 4.0.0
parameters:
  show-inherited-invariants: false
  version-comparison: n/a
# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided input/includes/menu.xml file, delete the "menu" property below.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
pages:
  index.md:
    title: Home
  message.md:
    title: Messages
  artifacts.html:
    title: Artifacts Summary
  downloads.md:
    title: Download Specification
  change_log.md:
    title: Change Log
menu:
  Home: index.html
  Artifacts:
    All FHIR Artifacts: artifacts.html
    Messages: message.html
    Other Downloads: downloads.html
  History:
    Change Log: change_log.html
    Other Versions: http://hl7.org/fhir/us/mcode/history.html
