# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/docs/sushi/configuration/                    │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: vital-records-fhir-messaging
canonical: http://cdc.gov/nchs/nvss/fhir/vital-records-messaging
name: VitalRecordsFHIRMessagingIG
title: Vital Records FHIR Messaging (VRFM) IG
status: draft
version: 1.0.0
copyrightYear: 2022+
releaseLabel: ci-build
publisher:
  name: CDC NCHS
  url: http://cdc.gov/nchs
license: CC0-1.0
fhirVersion: 4.0.1
dependencies:
  hl7.fhir.us.core: 5.0.1
  hl7.fhir.us.vrdr: current
parameters:
  show-inherited-invariants: false
  version-comparison: n/a
  path-expansion-params: '../../exp-params.json'  #path is relative to  [base]/fsh-generated/resources
# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided input/includes/menu.xml file, delete the "menu" property below.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
pages:
  index.md:
    title: Home
  message.md:
    title: Messages
  artifacts.html:
    title: Artifacts Summary
  downloads.md:
    title: Download Specification
  change_log.md:
    title: Change Log
  appendix.md:
    title: Appendices
  june2022testingeventexamples.md:
    title: June 2022 Testing Event Examples
  business_rules.md:
    title: NCHS Error Messages 
menu:
  Home: index.html
  Messages:
    Message Exchange Patterns: message.html#message-exchange-patterns
    Message Structure and Content: message.html#message-structure-and-content
    NCHS Error Messages: business_rules.html 
  Appendices: appendix.html
  Artifacts:
    All FHIR Artifacts: artifacts.html
    June 2022 Testing Event Examples: june2022testingeventexamples.html
    Other Downloads: downloads.html
  History:
    Change Log: change_log.html
groups:
  Messages:
    name: Message Profiles
    description: Message Profiles
    resources:
    - StructureDefinition/VRM-DeathRecordSubmissionMessage
    - StructureDefinition/VRM-DeathRecordUpdateMessage
    - StructureDefinition/VRM-DeathRecordVoidMessage
    - StructureDefinition/VRM-DeathRecordAliasMessage
    - StructureDefinition/VRM-CauseOfDeathCodingMessage
    - StructureDefinition/VRM-CauseOfDeathCodingUpdateMessage
    - StructureDefinition/VRM-DemographicsCodingMessage
    - StructureDefinition/VRM-DemographicsCodingUpdateMessage
    - StructureDefinition/VRM-AcknowledgementMessage
    - StructureDefinition/VRM-ExtractionErrorMessage
    - StructureDefinition/VRM-StatusMessage
  Headers:
    name: Message Header Profiles
    description: Message Header Profiles
    resources:
    - StructureDefinition/VRM-SubmissionHeader
    - StructureDefinition/VRM-UpdateHeader
    - StructureDefinition/VRM-VoidHeader
    - StructureDefinition/VRM-AliasHeader
    - StructureDefinition/VRM-StatusHeader
    - StructureDefinition/VRM-CauseOfDeathCodingHeader
    - StructureDefinition/VRM-CauseOfDeathCodingUpdateHeader
    - StructureDefinition/VRM-DemographicsCodingHeader
    - StructureDefinition/VRM-DemographicsCodingUpdateHeader
    - StructureDefinition/VRM-AcknowledgementHeader
    - StructureDefinition/VRM-ExtractionErrorHeader
  Parameters:
    name: Message Parameter Profiles
    description: Message Parameter Profiles
    resources:
    - StructureDefinition/VRM-MessageParameters
    - StructureDefinition/VRM-VoidParameters
    - StructureDefinition/VRM-AliasParameters
    - StructureDefinition/VRM-StatusParameters
  Outcomes:
    name: Outcome Profiles
    resources:
    - StructureDefinition/VRM-Outcome
  CodeSystems:
    name: Codesystems
    description: Codesystems
    resources:
    - CodeSystem/VRM-MessageHeaderURI-cs
