# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/docs/sushi/configuration/                    │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: vital-records-fhir-messaging
canonical: http://cdc.gov/nchs/nvss/fhir/vital-records-messaging
name: VitalRecordsFHIRMessagingIG
title: Vital Records FHIR Messaging IG
status: draft
version: 0.1.0
copyrightYear: 2021+
releaseLabel: ci-build
publisher:
  name: CDC NCHS
  url: http://cdc.gov/nchs
license: CC0-1.0
fhirVersion: 4.0.1
dependencies:
  hl7.fhir.us.core: 4.0.0
  hl7.fhir.us.vrdr: 1.2.0
parameters:
  show-inherited-invariants: false
  version-comparison: n/a
  path-expansion-params: '../../exp-params.json'  #path is relative to [base]/fsh-generated/resources
# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided input/includes/menu.xml file, delete the "menu" property below.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
pages:
  index.md:
    title: Home
  message.md:
    title: Messages
  artifacts.html:
    title: Artifacts Summary
  downloads.md:
    title: Download Specification
  change_log.md:
    title: Change Log
  appendix.md:
    title: Appendices
menu:
  Home: index.html
  Messages: message.html
  Appendices: appendix.html
  Artifacts:
    All FHIR Artifacts: artifacts.html
    Other Downloads: downloads.html
  History:
    Change Log: change_log.html
groups:
  Messages:
    name: Messages
    description: Messages
    resources:
    - StructureDefinition/VRM-DeathRecordSubmissionMessage
    - StructureDefinition/VRM-DeathRecordUpdateMessage
    - StructureDefinition/VRM-DeathRecordVoidMessage
    - StructureDefinition/VRM-DeathRecordAliasMessage
    - StructureDefinition/VRM-CauseOfDeathCodingMessage
    - StructureDefinition/VRM-CauseOfDeathCodingUpdateMessage
    - StructureDefinition/VRM-DemographicsCodingMessage
    - StructureDefinition/VRM-DemographicsCodingUpdateMessage
    - StructureDefinition/VRM-AcknowledgementMessage
    - StructureDefinition/VRM-ExtractionErrorMessage
  Headers:
    name: Headers
    description: Headers
  Parameters:
    name: Parameters
    description: Parameters
  CodeSystems:
    name: Codesystems
    description: Codesystems
  ValueSets:
    name: Valuesets
    description: Valuesets
